### ISSUE TITLE
Whatever folder with .sy1 Synth1 presets I want to create a database file with - I always get a 'Cannot convert non-finite values (NA or inf) to integer' error

### ISSUE THREAD

**Issue by ZonderP** [intrlocutr/patch1#1]
`PS D:\Dev\Dev\VST\patch1> python .
Drag and drop support is disabled. Consult the README for more information.
Traceback (most recent call last):
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "D:\Dev\Dev\VST\patch1\.\src\gui.py", line 513, in new_database_prompt
    self.new_database(new_dir)
  File "D:\Dev\Dev\VST\patch1\.\src\app.py", line 64, in inner
    ret = func(self, *args, **kwargs)
  File "D:\Dev\Dev\VST\patch1\.\src\app.py", line 230, in new_database
    self.__db.bootstrap(Path(patches_dir))
  File "D:\Dev\Dev\VST\patch1\.\src\data.py", line 63, in bootstrap
    param_df = pd.DataFrame(params, columns=self.schema.params,
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\frame.py", line 790, in __init__
    mgr = arrays_to_mgr(
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\internals\construction.py", line 120, in arrays_to_mgr
    arrays, refs = _homogenize(arrays, index, dtype)
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\internals\construction.py", line 607, in _homogenize
    val = sanitize_array(val, index, dtype=dtype, copy=False)
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\construction.py", line 576, in sanitize_array
    subarr = _try_cast(data, dtype, copy)
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\construction.py", line 763, in _try_cast
    subarr = maybe_cast_to_integer_array(arr, dtype)
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\dtypes\cast.py", line 1685, in maybe_cast_to_integer_array
    raise IntCastingNaNError(
pandas.errors.IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer
PS D:\Dev\Dev\VST\patch1>`

I'm on Windows and I think I did everything as described in the README.md.
I already tried to debug, but I'm all but a Python expert and the code in the libraries is way to complicated for me to understand...

**Comment by thomashuss** [comment]
This is due to a change in `pandas` in the last few months which I had not addressed until now; try pulling the latest commit and let me know if it works.

**Comment by ZonderP** [comment]
Wow, thanks Thomas for the quick fix!
With ~12616 sy1 files there was only a problem with one - stating that 'SOS NL2 Bank 07\053.sy1' is not properly formatted.
Any chance of supporting a mode, where instead of importing to the database a direct export to fxp would be possible - e.g. into the same folder where the sy1 is in?
[053.zip](https://github.com/thomashuss/patch1/files/13346436/053.zip)

**Comment by thomashuss** [comment]
The formatting bug should be fixed now. Patch1 currently supports exporting individual presets to fxp or sy1 using the buttons in the lower right; if you are referring to mass export, either to many fxp files or fxb, that's something I've thought of but haven't implemented yet.

**Comment by ZonderP** [comment]
Thanks!
Will try the new fix after pulling tomorrow morning.
Yes, I was referring to something like mass export - or even just instead of importing to the database to just write the fxp files. But maybe I manage to see how this could be done by myself - maybe with the help of some Python gurus I have available at work.

**Comment by ZonderP** [comment]
Thanks again!
As expected, now 'SOS NL2 Bank 07\053.sy1' could also be imported.
Didn't get any error anymore on ~16000 presets.
